name: 'Lock Threads'

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly.

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  lock-threads:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ github.token }}
          process-only: 'issues'
          issue-comment: >
            I'm going to lock this issue because it has been closed for _30 days_ ⏳. This helps me find and focus on the active issues.
            If you have found a problem that seems similar to this, please open a new issue and complete the issue template so I can capture all the details necessary to investigate further.
          issue-inactive-days: '30'
          pr-comment: >
            I'm going to lock this pull request because it has been closed for _30 days_ ⏳. This helps me find and focus on the active contributions.
            If you have found a problem that seems related to this change, please open a new issue and complete the issue template so I can capture all the details necessary to investigate further.
          pr-inactive-days: '30'